servers:
  order: "order-server"
  finance: "finance-server"
  gaetway: "gateway-server"

l_topic:
  order: "Log-Kafka-Topic-Order"
  finance: "Log-Kafka-Topic-Finance"
  gateway: "Log-Kafka-Topic-GetWay"

kafka:
  brokers: ["b-1.hudi-workshop-kafkaclu.vuyy8d.c2.kafka.us-east-2.amazonaws.com:9092"]
  timeout: 5

mysql:
  host: 127.0.0.1
  port: 3306
  user: root
  password: 123456
  is_debug: true

redis:
  host: 182.92.239.63 #127.0.0.1
  port: 6379
  password: #123456
  db: 0

etcd:
  host: [127.0.0.1:2379]
  user: root
  password: root123456
  dail_time_out: 10
  dail_keep_alive_time: 10

grpc:
  call_time_out: 10 #秒

verify_code:
  key: "VerifyCode:%s"
  expiration: 300 #秒

es:
  host: "http://182.92.239.63:9200"
  user: ""
  password: ""
  trace_log: ""
  err_log: ""
