servers:
  order: "order-server"
  finance: "finance-server"
  gaetway: "gateway-server"

l_topic:
  order: "Log-Kafka-Topic-Order"
  finance: "Log-Kafka-Topic-Finance"
  gateway: "Log-Kafka-Topic-GetWay"

kafka:
  brokers: [127.0.0.1:9092]
  timeout: 5

mysql:
  host: 127.0.0.1
  port: 3306
  user: root
  password: 123456
  is_debug: true